### ISSUE TITLE
ExifRead upgrade?

### ISSUE THREAD

**Issue by pdelong42** [specify/web-asset-server#4]
This uses a really old version of ExifRead (v1.1.0).  It seems that this is the version packaged by Ubuntu, however.

I'm running this on CentOS, which doesn't even have a package for ExifRead.  Because of this, I attempted to install it via PIP, but that only seems to have versions 1.3.0 through 2.1.1, inclusive.

In the end, I grabbed the v1.1.0 tarball from the project's GitHub page.  Perhaps supporting a more recent version of ExifRead is a possibility?  In that case, end-users would probably need to install it from PIP.

**Comment by benanhalt** [comment]
This was developed on Ubuntu 12.04LTS, which seems to have v1.0.8 of what was then called exif-py and was hosted on SourceForge.

Trusty (14.04) apparently has v1.1.0 and even Wily (15.10) will only be at v1.4.2!

Did you try running with any of the versions that were available through PIP?

**Comment by pdelong42** [comment]
I have not, but if I do, I'll let you know how it goes.
