### ISSUE TITLE
Please update instructions to include a SystemD init script

### ISSUE THREAD

**Issue by saiab-systems** [specify/web-asset-server#7]
This would make it useful for running on Ubuntu 16.04 as well as making this and the report runner able to co-exist on the same machine.

**Comment by benanhalt** [comment]
I added a section to the README with the systemd unit file that we have used on newer ubuntu systems.

**Comment by saiab-systems** [comment]
Ben, that's perfect. Thank you for addressing this so quickly!

**Comment by tvalero** [comment]
Dear all ( @benanhalt et al.), 
Do you plan to add a Docker distribution for the web asset server ? We plan to use Specify (end Specify 7) with a Docker environment.
It may be easier to install and operate than a standard Linux version.

For your information, I played with at https://github.com/tvalero/web-asset-server

br

**Comment by benanhalt** [comment]
@tvalero We don't have any specific plans with respect to Docker. I personally don't have any experience with it, but I will take a look at your fork. Were you able to get it to work as a Docker container?
